name: build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Run tests
        run: cargo test --verbose
